version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.2.2
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@db:5432/hs_code_api_test
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Set up database
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load

      - run:
          name: Run tests
          command: |
            bundle exec rspec
