version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2
        environment:
          RAILS_ENV: test
      - image: cimg/postgres:15.3 # 👈 khai báo thêm DB container
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: hs_code_api_test
          POSTGRES_PASSWORD: postgres
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Set up database
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load

      - run:
          name: Run tests
          command: |
            bundle exec rspec
