default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  host: db
  database: hs_code_api_development

test:
  <<: *default
  host: 127.0.0.1
  database: hs_code_api_test

production:
  primary: &primary_production
    <<: *default
    database: hs_code_api_production
    username: hs_code_api
    password: <%= ENV["HS_CODE_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: hs_code_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: hs_code_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: hs_code_api_production_cable
    migrations_paths: db/cable_migrate
