:concurrency: 5
:queues:
  - default
  - mailers
  - imports
  - exports

:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log

:environment: <%= Rails.env %>

# Redis configuration
:redis:
  :url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/0' %>
  :namespace: hs_code_api_<%= Rails.env %> 